# Generated by Django 5.0.7 on 2024-07-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(null=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'extras',
            },
        ),
    ]
