# Generated by Django 5.0.7 on 2024-07-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ini', models.DateTimeField()),
                ('date_end', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'educations',
            },
        ),
    ]
